/* tools/blob2c.c — turn a binary file into a const C array.
 *
 *   blob2c <input> <symbol> > out.c
 *
 * The output is `const unsigned char <symbol>[]` plus `<symbol>_len`. Because it
 * is const, it lands in read-only data, which on a microcontroller means flash.
 * Link it into the firmware and hand `&symbol` to build_transformer_from_blob:
 * that is "weights in flash," and it needs no filesystem at all.
 */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: %s <input> <symbol>\n", argv[0]);
        return 1;
    }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror(argv[1]); return 1; }
    const char *sym = argv[2];

    printf("/* generated by blob2c from %s. do not edit. */\n", argv[1]);
    printf("#include <stddef.h>\n\n");
    printf("const unsigned char %s[] = {\n", sym);

    int c;
    size_t n = 0;
    while ((c = fgetc(f)) != EOF) {
        printf("0x%02x,", (unsigned)c);
        if (++n % 16 == 0)
            printf("\n");
    }
    fclose(f);

    printf("\n};\nconst size_t %s_len = %zu;\n", sym, n);
    return 0;
}
